apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krypton-eng-usa-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: letsencrypt-asraas
spec:
  ingressClassName: nginx-asraas
  tls:
  - hosts:
    - nginx-asraas.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: nginx-asraas.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: krypton-eng-usa
            port:
              number: 8090